//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALCALDESPROV
    {
        public int PAIS { get; set; }
        public string DEPARTAMEN { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string NOMBRE { get; set; }
        public string NUM { get; set; }
        public string ESTADO { get; set; }
        public string DEPENDENCIA { get; set; }
    }
}
