//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNACION
    {
        public string ANOPRO { get; set; }
        public string MESPRO { get; set; }
        public string CODDIR { get; set; }
        public Nullable<decimal> MONASI { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string ESTADO { get; set; }
        public string TIPCOMB { get; set; }
    
        public virtual DIRECC DIRECC { get; set; }
    }
}
