//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYUDANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AYUDANTE()
        {
            this.AYUDANTE_PUESTO = new HashSet<AYUDANTE_PUESTO>();
        }
    
        public string CODAYUD { get; set; }
        public string NOMAYUD { get; set; }
        public string DIRAYUD { get; set; }
        public string TELFAYUD { get; set; }
        public string DOCIDE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AYUDANTE_PUESTO> AYUDANTE_PUESTO { get; set; }
    }
}
