//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYUDANTE_PUESTO
    {
        public string COD_PUESTO { get; set; }
        public string COD_MERCADO { get; set; }
        public string COD_LETRA { get; set; }
        public string COD_PASAJE { get; set; }
        public string CODAYUD { get; set; }
        public string COD_TIPRES { get; set; }
        public string ESTADO { get; set; }
        public string NUMRES { get; set; }
        public Nullable<System.DateTime> FECINI { get; set; }
        public Nullable<System.DateTime> FECTER { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
    
        public virtual AYUDANTE AYUDANTE { get; set; }
        public virtual TIP_RESOLUCION TIP_RESOLUCION { get; set; }
        public virtual PUESTO PUESTO { get; set; }
    }
}
