//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABECOBDANTE
    {
        public string PTOCOB { get; set; }
        public string SERDOC { get; set; }
        public string CLADOC { get; set; }
        public string NUMDOC { get; set; }
        public string ANODOC { get; set; }
        public string MESDOC { get; set; }
        public string CODCONT { get; set; }
        public string NOMCONT { get; set; }
        public string CODANA { get; set; }
        public Nullable<decimal> IMPBASE { get; set; }
        public Nullable<decimal> IMPIGV { get; set; }
        public Nullable<decimal> IMPMORA { get; set; }
        public Nullable<decimal> IMPTOTAL { get; set; }
        public Nullable<decimal> TIPCAM { get; set; }
        public Nullable<System.DateTime> FECHEMIS { get; set; }
        public string TIPMON { get; set; }
        public string GLOSA { get; set; }
        public string NUMCOMP { get; set; }
        public string USUANU { get; set; }
        public Nullable<System.DateTime> FECANU { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> CONTROL { get; set; }
        public string ESTADO { get; set; }
        public string FPAG { get; set; }
        public string ANOACT { get; set; }
        public Nullable<decimal> IMPRET { get; set; }
        public string FRETEN { get; set; }
        public string MOTEXTO { get; set; }
    }
}
