//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABEVEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CABEVEN()
        {
            this.DETEVEN = new HashSet<DETEVEN>();
        }
    
        public string NUMEVEN { get; set; }
        public string DESEVEN { get; set; }
        public Nullable<System.DateTime> FECEVEN { get; set; }
        public string LUGEVEN { get; set; }
        public string PROGEVEN { get; set; }
        public string MESA1 { get; set; }
        public string MESA2 { get; set; }
        public string MESA3 { get; set; }
        public string MESA4 { get; set; }
        public string MESA5 { get; set; }
        public string MESA6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETEVEN> DETEVEN { get; set; }
    }
}
