//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABERECIBO
    {
        public string COD_REC { get; set; }
        public string COD_CONTRI { get; set; }
        public Nullable<decimal> TOT_RECIBO { get; set; }
        public Nullable<System.DateTime> FEC_PAGO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FEC_EXTORNO { get; set; }
        public string GLOSA { get; set; }
        public string USUARIO { get; set; }
    }
}
