//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COB_TESORERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COB_TESORERIA()
        {
            this.NUM_COB = new HashSet<NUM_COB>();
        }
    
        public string COD_REC { get; set; }
        public string COD_CONTRI { get; set; }
        public string COD_CONC { get; set; }
        public string NUM_RECIBO { get; set; }
        public Nullable<decimal> TOT_RECIBO { get; set; }
        public Nullable<System.DateTime> FEC_PAGO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FEC_EXTORNO { get; set; }
        public string COD_SISTEMA { get; set; }
        public string GLOSA { get; set; }
        public string CODTIP { get; set; }
        public string NUM_CHEQUE { get; set; }
        public string CODBAN { get; set; }
        public string TIPMON { get; set; }
        public string USUARIO { get; set; }
        public string CODANA { get; set; }
        public string NOMCONTRIB { get; set; }
        public string TIPTRA { get; set; }
        public string TIPTAB { get; set; }
        public string NUMCPA { get; set; }
        public string FLAGORIG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUM_COB> NUM_COB { get; set; }
    }
}
