//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTOR_PUESTO
    {
        public string COD_PASAJE { get; set; }
        public string COD_PUESTO { get; set; }
        public string COD_LETRA { get; set; }
        public string COD_MERCADO { get; set; }
        public string DOC_IDENTIDAD { get; set; }
        public string ESTADO { get; set; }
        public string NUM_RESOLUCION { get; set; }
        public string COD_ESTADO { get; set; }
        public string COD_MOTIVO { get; set; }
        public Nullable<System.DateTime> FEC_EMISIONRES { get; set; }
        public Nullable<System.DateTime> FEC_VENCRES { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string COD_TIPRES { get; set; }
        public string NUM_CONTRATO { get; set; }
        public string ANO_CONTRATO { get; set; }
        public Nullable<System.DateTime> INI_CONTRATO { get; set; }
        public Nullable<System.DateTime> FIN_CONTRATO { get; set; }
        public string USU_CONTRATO { get; set; }
        public Nullable<System.DateTime> FEC_CONTRATO { get; set; }
        public Nullable<decimal> MON_CONTRATO { get; set; }
        public string USUBLOQ { get; set; }
        public Nullable<System.DateTime> FECBLOQ { get; set; }
        public string OBSBLOQ { get; set; }
        public string OBSERVA { get; set; }
        public string AUTPAGO { get; set; }
        public Nullable<decimal> PEN_CONTRATO { get; set; }
        public string TERMINAL { get; set; }
        public string USERNAME { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual ESTADO_PROCESO ESTADO_PROCESO { get; set; }
        public virtual TIP_RESOLUCION TIP_RESOLUCION { get; set; }
        public virtual PUESTO PUESTO { get; set; }
    }
}
