//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDUCTOR()
        {
            this.CONDUCTOR_PUESTO = new HashSet<CONDUCTOR_PUESTO>();
        }
    
        public string DOC_IDENTIDAD { get; set; }
        public string TIP_DOC { get; set; }
        public string COD_DIST { get; set; }
        public string COD_VIA { get; set; }
        public Nullable<short> COD_NUMUN { get; set; }
        public string COD_ASTER { get; set; }
        public string DES_CONT { get; set; }
        public string COD_FAX { get; set; }
        public string COD_DEP { get; set; }
        public string COD_NOMBRE { get; set; }
        public string COD_TIPOPRO { get; set; }
        public string COD_RESOLU { get; set; }
        public string CANO_2 { get; set; }
        public string CUSUARIO_3 { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string COD_TIPMOD { get; set; }
        public string TIPO1 { get; set; }
        public string COD1 { get; set; }
        public string FLAG1 { get; set; }
        public string FLAG2 { get; set; }
        public string FLAG3 { get; set; }
        public string FLAG4 { get; set; }
        public string MERCADO { get; set; }
        public string CFLAG { get; set; }
        public string DIRECCION { get; set; }
        public string DISTRITO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONDUCTOR_PUESTO> CONDUCTOR_PUESTO { get; set; }
    }
}
