//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRELAT
    {
        public string PTOCOB { get; set; }
        public string CLADOC { get; set; }
        public string SERDOC { get; set; }
        public Nullable<int> NUMDOC { get; set; }
    }
}
