//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATACT()
        {
            this.SERV_REP = new HashSet<SERV_REP>();
            this.DEPACT = new HashSet<DEPACT>();
        }
    
        public string CODGEN { get; set; }
        public string CODESP { get; set; }
        public string CODART { get; set; }
        public string TIPBIE { get; set; }
        public string NUMSEC { get; set; }
        public string CODEST { get; set; }
        public string CODCTA { get; set; }
        public string NUMPART { get; set; }
        public string ORDCOM { get; set; }
        public string JEFGES { get; set; }
        public string UNIEJE { get; set; }
        public string CCANTE { get; set; }
        public string CENCOS { get; set; }
        public string PROVEE { get; set; }
        public Nullable<System.DateTime> FECCON { get; set; }
        public Nullable<System.DateTime> FECADQ { get; set; }
        public string NUMFAC { get; set; }
        public Nullable<decimal> VALCOM { get; set; }
        public Nullable<decimal> VALLIB { get; set; }
        public Nullable<decimal> DIFEREN { get; set; }
        public Nullable<System.DateTime> FULREV { get; set; }
        public Nullable<decimal> VIDUTI { get; set; }
        public string UBIREF { get; set; }
        public string OBSACT { get; set; }
        public string ESTACT { get; set; }
        public string RESPONSABLE { get; set; }
        public string USUARI { get; set; }
        public Nullable<System.DateTime> FCONTR { get; set; }
        public Nullable<System.DateTime> FECASIG { get; set; }
        public Nullable<System.DateTime> FECBAJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERV_REP> SERV_REP { get; set; }
        public virtual ESPACT ESPACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPACT> DEPACT { get; set; }
        public virtual MOVACT MOVACT { get; set; }
    }
}
