//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETCOB
    {
        public string CLADOC { get; set; }
        public string NUMDOC { get; set; }
        public string MESDOC { get; set; }
        public string ANODOC { get; set; }
        public string TIPTAB { get; set; }
        public string TIPTRA { get; set; }
        public string CODING { get; set; }
        public string INDAAN { get; set; }
        public string PTOCOB { get; set; }
        public string SERDOC { get; set; }
        public string NUMORD { get; set; }
        public Nullable<short> CANTI { get; set; }
        public Nullable<decimal> BASDET { get; set; }
        public Nullable<decimal> IGVDET { get; set; }
        public Nullable<decimal> MORDET { get; set; }
        public Nullable<decimal> TOTDET { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> CONTROL { get; set; }
        public string ESTADO { get; set; }
        public string ANODEU { get; set; }
        public string MESDEU { get; set; }
        public string ANOACT { get; set; }
        public Nullable<decimal> PRECUNI { get; set; }
        public string CODADIC { get; set; }
    }
}
