//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETMENU
    {
        public string CODCAB { get; set; }
        public string CODET { get; set; }
        public string DESDET { get; set; }
        public string PANDET { get; set; }
    
        public virtual CABMENU CABMENU { get; set; }
    }
}
