//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETPAG
    {
        public string PTOCOB { get; set; }
        public string SERDOC { get; set; }
        public string CLADOC { get; set; }
        public string NUMDOC { get; set; }
        public string MESDOC { get; set; }
        public string ANODOC { get; set; }
        public string NUMORD { get; set; }
        public string NUM { get; set; }
        public string CODTIP { get; set; }
        public Nullable<decimal> MONSOL { get; set; }
        public string CODBAN { get; set; }
        public string NUMCHE { get; set; }
        public Nullable<decimal> MONDOL { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> CONTROL { get; set; }
        public string ESTADO { get; set; }
    }
}
