//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETRECA
    {
        public string C_TRIBUT { get; set; }
        public string C_ANOPAG { get; set; }
        public string C_MESPAG { get; set; }
        public string C_ANO { get; set; }
        public string C_PERI { get; set; }
        public string C_TIPINT { get; set; }
        public decimal N_EMISIO { get; set; }
        public decimal N_REAJUS { get; set; }
        public decimal N_MORA { get; set; }
        public decimal N_TIM { get; set; }
        public System.DateTime F_VENCI { get; set; }
        public byte N_PRORRO { get; set; }
        public string C_USUARIO { get; set; }
        public System.DateTime F_CONTROL { get; set; }
        public string C_TIPOEMI2 { get; set; }
    }
}
