//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F121
    {
        public string PUESTO { get; set; }
        public string LETRA { get; set; }
        public string PASAJE { get; set; }
        public string NOMBRE { get; set; }
        public string CANO { get; set; }
        public string PERIODO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> MORA { get; set; }
    }
}
