//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACAJUS
    {
        public string ANOAJUS { get; set; }
        public string MESAJUS { get; set; }
        public Nullable<decimal> FACAJUSP { get; set; }
        public Nullable<decimal> FACAJUST { get; set; }
        public Nullable<decimal> FACDEPP { get; set; }
        public Nullable<decimal> FACDEPT { get; set; }
    }
}
