//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICONTC
    {
        public string CB_DOCIDEN { get; set; }
        public string CB_TIPODOC { get; set; }
        public string CB_DIST { get; set; }
        public string CB_CODVIA { get; set; }
        public Nullable<decimal> CB_NUMUN { get; set; }
        public string CB_ASTER { get; set; }
        public string CB_IDEN { get; set; }
        public string CB_DESCRIP { get; set; }
        public string CB_FAX { get; set; }
        public string CB_DEP { get; set; }
        public string CB_NOMBRE { get; set; }
        public string CB_TIPOPRO { get; set; }
        public string CB_RESOLU { get; set; }
        public string CB_ANO { get; set; }
        public string CB_CODUSU { get; set; }
        public Nullable<System.DateTime> CB_FECHAMO { get; set; }
        public string CB_TIPOMOD { get; set; }
        public string CB_TIPO1 { get; set; }
        public string CB_DOC1 { get; set; }
        public string FLAG1 { get; set; }
        public string FLAG2 { get; set; }
        public string FLAG3 { get; set; }
        public string FLAG4 { get; set; }
        public string MERCADO { get; set; }
        public string TIPX { get; set; }
    }
}
