//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRONTECU
    {
        public string VOCATIVO { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CARGO { get; set; }
        public string DEPARTAMEN { get; set; }
        public string COD_DPTO { get; set; }
        public string PAIS { get; set; }
        public string COD_PAIS { get; set; }
    }
}
