//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGGRI
    {
        public string CODGRI { get; set; }
        public System.DateTime FECING { get; set; }
        public string MESPRO { get; set; }
        public string ANOPRO { get; set; }
        public string TIPCOMB { get; set; }
        public string REFERENCIA { get; set; }
        public string NUMFAC { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string CODCOMB { get; set; }
        public Nullable<decimal> PREUNI { get; set; }
    
        public virtual GRIDIS GRIDIS { get; set; }
        public virtual TIPCOMB TIPCOMB1 { get; set; }
    }
}
