//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGRA02B
    {
        public string NUMDOC { get; set; }
        public Nullable<decimal> BASDET { get; set; }
        public Nullable<decimal> MORDET { get; set; }
        public string GLOSA { get; set; }
        public string CODING { get; set; }
    }
}
