//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORA120
    {
        public string COD_PASAJE { get; set; }
        public string C_ID { get; set; }
        public string COD_LETRA { get; set; }
        public string COD_PUESTO { get; set; }
        public string CANO { get; set; }
        public string COD_MERCADO { get; set; }
        public string PERIODO { get; set; }
        public int NUM_CTACTE { get; set; }
        public string CODCON1 { get; set; }
        public string CODCON2 { get; set; }
        public Nullable<decimal> VALOR1 { get; set; }
        public Nullable<decimal> EMISION { get; set; }
        public string CAJA { get; set; }
        public Nullable<System.DateTime> FEC_CANCELACION { get; set; }
        public string NUM_CANCELACION { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public Nullable<decimal> REAJUSTE { get; set; }
        public Nullable<decimal> MORA { get; set; }
        public string ANO_CANCELACION { get; set; }
        public string MES_CANCELACION { get; set; }
        public string FLGUBI { get; set; }
    }
}
