//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORA_MARZO
    {
        public string CODTRI { get; set; }
        public string ANOPER { get; set; }
        public string MESPER { get; set; }
        public Nullable<System.DateTime> FECVENC { get; set; }
        public Nullable<decimal> TASMOR { get; set; }
        public string USUARIO { get; set; }
        public string TIPOACT { get; set; }
        public Nullable<System.DateTime> CONTROL { get; set; }
        public string ESTADO { get; set; }
    }
}
