//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVACF
    {
        public string ANOASI { get; set; }
        public string MESASI { get; set; }
        public string CODCOM { get; set; }
        public string CODASI { get; set; }
        public string NUMASI { get; set; }
        public string SECUEN { get; set; }
        public string CODCTA { get; set; }
        public string TIPANA { get; set; }
        public Nullable<System.DateTime> FECASI { get; set; }
        public string DESASI { get; set; }
        public string TIPDOC { get; set; }
        public string NUMDOC { get; set; }
        public string CODANA { get; set; }
        public string NUMREF { get; set; }
        public Nullable<decimal> IMPASI { get; set; }
        public string ACCASI { get; set; }
        public Nullable<System.DateTime> FECVEN { get; set; }
        public Nullable<decimal> IMPASD { get; set; }
        public Nullable<decimal> TPOCAM { get; set; }
        public string TPOMON { get; set; }
        public string JEFGES { get; set; }
        public string UNDEJE { get; set; }
        public string CENCOS { get; set; }
        public string CLAGAS { get; set; }
        public string CLAFUN { get; set; }
        public string CLAPRO { get; set; }
        public string CLASUP { get; set; }
        public string FLAGAP { get; set; }
        public string CODAPY { get; set; }
        public string ESTASI { get; set; }
        public string USUARI { get; set; }
        public Nullable<System.DateTime> FCONTR { get; set; }
        public string FLGCTB { get; set; }
        public string SBPGES { get; set; }
        public string FTEFIN { get; set; }
        public string NUMORC { get; set; }
        public Nullable<System.DateTime> FECORC { get; set; }
        public string TIPORD { get; set; }
    }
}
