//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVACT
    {
        public string CODTIP { get; set; }
        public string CODGEN { get; set; }
        public string CODESP { get; set; }
        public string ORDCOM { get; set; }
        public string JEFGES { get; set; }
        public string CODART { get; set; }
        public string UNIEJE { get; set; }
        public string TIPBIE { get; set; }
        public string CENCOS { get; set; }
        public string NUMSEC { get; set; }
        public string PROVEE { get; set; }
        public Nullable<System.DateTime> FECCON { get; set; }
        public string NUMFAC { get; set; }
        public Nullable<decimal> VALCOM { get; set; }
        public Nullable<decimal> VALLIB { get; set; }
        public Nullable<decimal> VNELIB { get; set; }
        public string DESTEC { get; set; }
        public string NUMPLA { get; set; }
        public string CODMAR { get; set; }
        public string ANOFAB { get; set; }
        public string CODCOM { get; set; }
        public string CODMAT { get; set; }
        public string CODCOL { get; set; }
        public string NUMMOT { get; set; }
        public string NUMSER { get; set; }
        public Nullable<decimal> LONGIT { get; set; }
        public Nullable<decimal> ALTURA { get; set; }
        public Nullable<decimal> ANCHOS { get; set; }
        public Nullable<System.DateTime> FECREC { get; set; }
        public string NUMFIL { get; set; }
        public string NUMCON { get; set; }
        public Nullable<System.DateTime> FECMAR { get; set; }
        public string ESTMOV { get; set; }
        public string USUARI { get; set; }
        public Nullable<System.DateTime> FCONTR { get; set; }
        public Nullable<System.DateTime> FECADQ { get; set; }
        public string RESPONSABLE { get; set; }
        public Nullable<System.DateTime> FECENV { get; set; }
    
        public virtual DATACT DATACT { get; set; }
    }
}
