//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVING03
    {
        public Nullable<System.DateTime> FECASI { get; set; }
        public string CAJERO { get; set; }
        public string CODING { get; set; }
        public string ESTADO { get; set; }
        public string ANOASI { get; set; }
        public string MESASI { get; set; }
        public string CODCOM { get; set; }
        public string CODASI { get; set; }
        public string CODCTA { get; set; }
        public string NUMASI { get; set; }
        public string CODANA { get; set; }
        public string DESASI { get; set; }
        public string TIPDOC { get; set; }
        public string NUMREF { get; set; }
        public Nullable<decimal> IMPASI { get; set; }
        public string ACCASI { get; set; }
        public Nullable<System.DateTime> FECVEN { get; set; }
        public Nullable<decimal> IMPASID { get; set; }
        public Nullable<decimal> TIPCAM { get; set; }
        public string TIPMON { get; set; }
        public string USUARIO { get; set; }
        public string JEFGES { get; set; }
        public string UNIEJE { get; set; }
        public string CENCOS { get; set; }
        public string CLAGAS { get; set; }
        public string FUNCIO { get; set; }
        public string PROGRA { get; set; }
        public string SUBPRO { get; set; }
        public string FLAGACP { get; set; }
        public string CODACTP { get; set; }
        public string FLGCTB { get; set; }
        public string CODTAR { get; set; }
        public string CODFTE { get; set; }
        public string ANOPAG { get; set; }
        public string CODBAN { get; set; }
        public string TIPTRA { get; set; }
        public string NUMDOC { get; set; }
        public string TIPTAB { get; set; }
        public string INDAAN { get; set; }
        public string LUGCOB { get; set; }
        public string NUMCPA { get; set; }
        public string SECUEN { get; set; }
        public string CODIGO { get; set; }
        public string MERCADO { get; set; }
        public string CONCEPTO { get; set; }
    }
}
