//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVVEH
    {
        public string TIPMOV { get; set; }
        public string NUMDOC { get; set; }
        public Nullable<System.DateTime> FECDOC { get; set; }
        public string CODVEH { get; set; }
        public string CONDUC { get; set; }
        public string COMBUS { get; set; }
        public Nullable<decimal> CANTID { get; set; }
        public Nullable<decimal> KILOME { get; set; }
        public string OBSERV { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string ESTADO { get; set; }
        public string CODPIL { get; set; }
        public string CODGRI { get; set; }
    
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
