//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUM_COB
    {
        public string COD_AUT { get; set; }
        public string COD_REC { get; set; }
        public Nullable<decimal> CANT { get; set; }
        public Nullable<System.DateTime> FEC_DEUDA { get; set; }
        public Nullable<decimal> INT_MORA { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public string COD_CONC { get; set; }
        public string ESTADO { get; set; }
        public string TIPMON { get; set; }
        public string CODBAN { get; set; }
        public string FORPAG { get; set; }
        public Nullable<decimal> IMPDOLARES { get; set; }
        public Nullable<decimal> TIPCAMB { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
    
        public virtual COB_TESORERIA COB_TESORERIA { get; set; }
    }
}
