//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_DEPENDENCIA_P
    {
        public string COD_PERS { get; set; }
        public string COD_DEP { get; set; }
        public string CAR_PERS { get; set; }
        public string CENTLAB { get; set; }
        public string DIRECC { get; set; }
        public string TELF_PERS { get; set; }
        public string COD_PAIS { get; set; }
        public string COD_DPTO { get; set; }
        public string COD_PROV { get; set; }
        public string COD_DIST { get; set; }
        public string CODPOST { get; set; }
    
        public virtual DEPENDENCIA_P DEPENDENCIA_P { get; set; }
        public virtual DISTRITO_P DISTRITO_P { get; set; }
        public virtual PERSONAL_P PERSONAL_P { get; set; }
    }
}
