//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        public string COD_PERS { get; set; }
        public string COD_DEP { get; set; }
        public string COD_DIST { get; set; }
        public string COD_PROV { get; set; }
        public string COD_DPTO { get; set; }
        public string COD_PAIS { get; set; }
        public string COD_PROF { get; set; }
        public string NOM_PERS { get; set; }
        public string APE_PERS { get; set; }
        public string CAR_PERS { get; set; }
        public Nullable<System.DateTime> FEC_NAC { get; set; }
        public string TELF_PERS { get; set; }
        public string TRATO { get; set; }
        public string DIRECC { get; set; }
        public string ESTCIV { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string USUARIO { get; set; }
        public string CENTLAB { get; set; }
        public string SEXO { get; set; }
        public string CODPOST { get; set; }
        public string SITE { get; set; }
    
        public virtual DEPENDENCIA DEPENDENCIA { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual PROFESION PROFESION { get; set; }
    }
}
