//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_P
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAL_P()
        {
            this.PERSONAL_DEPENDENCIA_P = new HashSet<PERSONAL_DEPENDENCIA_P>();
        }
    
        public string COD_PERS { get; set; }
        public string NOM_PERS { get; set; }
        public string APE_PERS { get; set; }
        public Nullable<System.DateTime> FEC_NAC { get; set; }
        public string TRATO { get; set; }
        public string ESTCIV { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string USUARIO { get; set; }
        public string SEXO { get; set; }
        public string SITE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAL_DEPENDENCIA_P> PERSONAL_DEPENDENCIA_P { get; set; }
    }
}
