//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILOTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PILOTO()
        {
            this.PILVEH = new HashSet<PILVEH>();
        }
    
        public string CODPIL { get; set; }
        public string NOMPIL { get; set; }
        public string DIRPIL { get; set; }
        public string TELPIL { get; set; }
        public string LIBPIL { get; set; }
        public string OTRPIL { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string CODDIR { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PILVEH> PILVEH { get; set; }
    }
}
