//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILVEH_TEMP
    {
        public string CODPIL { get; set; }
        public string CODVEH { get; set; }
        public string NUMCOR { get; set; }
        public Nullable<System.DateTime> FASING { get; set; }
        public string NOMPIL { get; set; }
        public string NUMDOC { get; set; }
        public string CODCOMB { get; set; }
        public string CODDIR { get; set; }
    }
}
