//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINC
    {
        public string DEPARTAMEN { get; set; }
        public string PROVINCIA_ { get; set; }
        public string GRUPO_POLI { get; set; }
        public string A_PATERNO { get; set; }
        public string A_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO_F { get; set; }
        public string COD_PERS { get; set; }
        public string COD_DEP { get; set; }
        public string COD_PAIS { get; set; }
        public string COD_DPTO { get; set; }
        public string COD_PROV { get; set; }
        public string COD_DIST { get; set; }
    }
}
