//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEED
    {
        public string PV_CODIGO { get; set; }
        public string PV_RUC { get; set; }
        public string PV_RAZSOC { get; set; }
        public string PV_DIRECC { get; set; }
        public string PV_TEL { get; set; }
        public string PV_DISTRI { get; set; }
        public string PV_CODUSU { get; set; }
        public System.DateTime PV_FCHMOD { get; set; }
        public string PV_TIPMOD { get; set; }
    }
}
