//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTO_EMP2004
    {
        public string COD_PUESTO { get; set; }
        public string COD_MERCADO { get; set; }
        public string COD_LETRA { get; set; }
        public string COD_PASAJE { get; set; }
        public string NUMFIC { get; set; }
        public string ACTCONDUCTOR { get; set; }
        public string ACTDOMICILIO { get; set; }
        public string ACTDISTRITO { get; set; }
        public string ACTEDAD { get; set; }
        public string ACTDNI { get; set; }
        public string ACTRUC { get; set; }
        public string ACTSALUD { get; set; }
        public Nullable<System.DateTime> ACTVENSALUD { get; set; }
        public string VINCULO { get; set; }
        public string GIROACT { get; set; }
        public string SITUACION { get; set; }
        public string AREA { get; set; }
        public string SUMINISTRO { get; set; }
        public string TELEFONO { get; set; }
        public string MATERIAL { get; set; }
        public string PISOS { get; set; }
        public string REGULARIZACION { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public string RECONSIDERACION { get; set; }
        public Nullable<System.DateTime> FECREC { get; set; }
        public string VACANCIA { get; set; }
        public Nullable<System.DateTime> FECVAC { get; set; }
        public string AUSENCIA { get; set; }
        public Nullable<System.DateTime> FECAUS { get; set; }
        public string AYUDANTE { get; set; }
        public Nullable<System.DateTime> FECAYU { get; set; }
        public string REFACCION { get; set; }
        public Nullable<System.DateTime> FECREF { get; set; }
        public string AYUDNI1 { get; set; }
        public string AYUNOMBRES1 { get; set; }
        public string AYUEDAD1 { get; set; }
        public string AYURESOLUCION1 { get; set; }
        public string AYUSALUD1 { get; set; }
        public string AYUDNI2 { get; set; }
        public string AYUNOMBRES2 { get; set; }
        public string AYUEDAD2 { get; set; }
        public string AYURESOLUCION2 { get; set; }
        public string AYUSALUD2 { get; set; }
        public string AYUDNI3 { get; set; }
        public string AYUNOMBRES3 { get; set; }
        public string AYUEDAD3 { get; set; }
        public string AYURESOLUCION3 { get; set; }
        public string AYUSALUD3 { get; set; }
        public string OBSERVA { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string USUARIO { get; set; }
    
        public virtual PUESTO PUESTO { get; set; }
    }
}
