//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPUEST
    {
        public string RP_CODIGO { get; set; }
        public string RP_DESCRI { get; set; }
        public string RP_DESCOR { get; set; }
        public string RP_UMEDID { get; set; }
        public string RP_COMPON { get; set; }
        public string RP_CODUSU { get; set; }
        public System.DateTime RP_FCHMOD { get; set; }
        public string RP_TIPMOD { get; set; }
    }
}
