//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALGRI
    {
        public string ANOPRO { get; set; }
        public string CODGRI { get; set; }
        public string MESPRO { get; set; }
        public string CODCOMB { get; set; }
        public Nullable<decimal> CANING { get; set; }
        public Nullable<decimal> CANDES { get; set; }
    
        public virtual GRIDIS GRIDIS { get; set; }
        public virtual TIPCOMB TIPCOMB { get; set; }
    }
}
