//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTAB
    {
        public string SIS_NUMTAB { get; set; }
        public string SIS_NUMELE { get; set; }
        public string SIS_DESLAR { get; set; }
        public string SIS_DESCOR { get; set; }
        public decimal SIS_VALCOR { get; set; }
        public string SIS_MES { get; set; }
    }
}
