//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRES
    {
        public string COD_PASAJE { get; set; }
        public string COD_PUESTO { get; set; }
        public string COD_LETRA { get; set; }
        public string PERIODO { get; set; }
        public string CANO { get; set; }
        public Nullable<decimal> INTTOT { get; set; }
        public string COD_MERCADO { get; set; }
        public Nullable<decimal> DESINI { get; set; }
        public Nullable<decimal> DEUTOT { get; set; }
        public string TIPPAG { get; set; }
        public Nullable<decimal> MONPRI { get; set; }
    }
}
