//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDOALM
    {
        public string TPODOC { get; set; }
        public string DESDOC { get; set; }
        public string TIPMOV { get; set; }
        public string USUARI { get; set; }
        public Nullable<System.DateTime> FCONTR { get; set; }
    }
}
