//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP84
    {
        public string COD_PUESTO { get; set; }
        public string COD_LETRA { get; set; }
        public string COD_MERCADO { get; set; }
        public string COD_PASAJE { get; set; }
        public string COD_CODCON { get; set; }
        public Nullable<decimal> NRO_AREA { get; set; }
        public string COD_GIRO { get; set; }
        public string COD_ACTIVI { get; set; }
        public string COD_CATEGO { get; set; }
        public string COD_NUMRES { get; set; }
        public string CUSUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string XGIR { get; set; }
        public string XACT { get; set; }
        public string ESTADO { get; set; }
        public string COD_GIROACT { get; set; }
        public string COD_ACTIVIACT { get; set; }
        public string COD_CONDICION { get; set; }
        public string FLGHAB { get; set; }
        public string CODCAT { get; set; }
    }
}
