//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIP_RESOLUCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIP_RESOLUCION()
        {
            this.AYUDANTE_PUESTO = new HashSet<AYUDANTE_PUESTO>();
            this.CONDUCTOR_PUESTO = new HashSet<CONDUCTOR_PUESTO>();
        }
    
        public string COD_TIPRES { get; set; }
        public string DES_TIPRES { get; set; }
        public string ABREV_TIPRES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AYUDANTE_PUESTO> AYUDANTE_PUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONDUCTOR_PUESTO> CONDUCTOR_PUESTO { get; set; }
    }
}
