//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ACCESO = new HashSet<ACCESO>();
        }
    
        public string CODIGO { get; set; }
        public string PASSWO { get; set; }
        public string NOMBRE { get; set; }
        public string ABREVI { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public string CARGO { get; set; }
        public string NIVEL { get; set; }
        public string OFICINA { get; set; }
        public string ESTADO { get; set; }
        public string C_USUARIO { get; set; }
        public Nullable<System.DateTime> F_CONTROL { get; set; }
        public string COD_MERCADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESO> ACCESO { get; set; }
    }
}
