//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.MOVVEH = new HashSet<MOVVEH>();
            this.PILVEH = new HashSet<PILVEH>();
        }
    
        public string CODVEH { get; set; }
        public string CODMOT { get; set; }
        public string CODDIR { get; set; }
        public string NUMINT { get; set; }
        public string CODCOMB { get; set; }
        public string CODCOL { get; set; }
        public string CODMAR { get; set; }
        public string NUMMOT { get; set; }
        public string DESCRI { get; set; }
        public string CODTIP { get; set; }
        public string NUMSER { get; set; }
        public string ANO { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FCONTROL { get; set; }
        public string PLACA { get; set; }
        public string MODELO { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        public virtual DIRECC DIRECC { get; set; }
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVVEH> MOVVEH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PILVEH> PILVEH { get; set; }
        public virtual TIPCOMB TIPCOMB { get; set; }
        public virtual TIPMOT TIPMOT { get; set; }
        public virtual TIPVEH TIPVEH { get; set; }
    }
}
