//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MML_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIA
    {
        public string COD_VIA { get; set; }
        public string VIA1 { get; set; }
        public string COD_DIST { get; set; }
        public string NOM_VIA { get; set; }
        public string PLANO { get; set; }
        public string LETRA { get; set; }
        public string NUMERO { get; set; }
    
        public virtual DISTRITOS DISTRITOS { get; set; }
    }
}
